#############################################################################
# Makefile for building: bin/autoed
# Generated by qmake (3.0) (Qt 5.6.2)
# Project:  autoed.pro
# Template: app
# Command: /home/ad/anaconda3/bin/qmake -o Makefile autoed.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++0x -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /home/ad/anaconda3/include/qt -isystem /home/ad/anaconda3/include/qt/QtWidgets -isystem /home/ad/anaconda3/include/qt/QtGui -isystem /home/ad/anaconda3/include/qt/QtCore -Ibuild/moc -Ibuild/uic -I/home/ad/anaconda3/mkspecs/linux-g++
QMAKE         = /home/ad/anaconda3/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = autoed1.0.0
DISTDIR = /media/ad/Area51/workspace/assignments/cop290/build/obj/autoed1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/ad/anaconda3/lib
LIBS          = $(SUBLIBS) -larmadillo -lQt5Widgets -L/home/ad/anaconda3/lib -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = build/obj/

####### Files

SOURCES       = src/main.cpp \
		src/mainwindow.cpp build/moc/moc_mainwindow.cpp
OBJECTS       = build/obj/main.o \
		build/obj/mainwindow.o \
		build/obj/moc_mainwindow.o
DIST          = /home/ad/anaconda3/mkspecs/features/spec_pre.prf \
		/home/ad/anaconda3/mkspecs/common/unix.conf \
		/home/ad/anaconda3/mkspecs/common/linux.conf \
		/home/ad/anaconda3/mkspecs/common/sanitize.conf \
		/home/ad/anaconda3/mkspecs/common/gcc-base.conf \
		/home/ad/anaconda3/mkspecs/common/gcc-base-unix.conf \
		/home/ad/anaconda3/mkspecs/common/g++-base.conf \
		/home/ad/anaconda3/mkspecs/common/g++-unix.conf \
		/home/ad/anaconda3/mkspecs/qconfig.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_clucene_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_concurrent.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_core.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_core_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_dbus.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_designer.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_designer_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_gui.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_gui_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_help.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_help_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_multimedia.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_network.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_network_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_nfc.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_opengl.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_printsupport.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_qml.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_qml_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_qmltest.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_quick.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_quick_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_script.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_script_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_scripttools.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_scripttools_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_sql.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_sql_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_svg.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_svg_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_testlib.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_uitools.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_webchannel.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_webkit.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_webkit_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_websockets.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_widgets.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_x11extras.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_xml.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_xml_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/ad/anaconda3/mkspecs/features/qt_functions.prf \
		/home/ad/anaconda3/mkspecs/features/qt_config.prf \
		/home/ad/anaconda3/mkspecs/linux-g++/qmake.conf \
		/home/ad/anaconda3/mkspecs/features/spec_post.prf \
		/home/ad/anaconda3/mkspecs/features/exclusive_builds.prf \
		/home/ad/anaconda3/mkspecs/features/default_pre.prf \
		/home/ad/anaconda3/mkspecs/features/resolve_config.prf \
		/home/ad/anaconda3/mkspecs/features/default_post.prf \
		/home/ad/anaconda3/mkspecs/features/warn_on.prf \
		/home/ad/anaconda3/mkspecs/features/qt.prf \
		/home/ad/anaconda3/mkspecs/features/resources.prf \
		/home/ad/anaconda3/mkspecs/features/moc.prf \
		/home/ad/anaconda3/mkspecs/features/unix/opengl.prf \
		/home/ad/anaconda3/mkspecs/features/uic.prf \
		/home/ad/anaconda3/mkspecs/features/unix/thread.prf \
		/home/ad/anaconda3/mkspecs/features/file_copies.prf \
		/home/ad/anaconda3/mkspecs/features/testcase_targets.prf \
		/home/ad/anaconda3/mkspecs/features/exceptions.prf \
		/home/ad/anaconda3/mkspecs/features/yacc.prf \
		/home/ad/anaconda3/mkspecs/features/lex.prf \
		autoed.pro include/mainwindow.h \
		include/struct.h src/main.cpp \
		src/mainwindow.cpp
QMAKE_TARGET  = autoed
DESTDIR       = bin/
TARGET        = bin/autoed


first: all
####### Build rules

$(TARGET): build/uic/ui_mainwindow.h $(OBJECTS)  
	@test -d bin/ || mkdir -p bin/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: autoed.pro /home/ad/anaconda3/mkspecs/linux-g++/qmake.conf /home/ad/anaconda3/mkspecs/features/spec_pre.prf \
		/home/ad/anaconda3/mkspecs/common/unix.conf \
		/home/ad/anaconda3/mkspecs/common/linux.conf \
		/home/ad/anaconda3/mkspecs/common/sanitize.conf \
		/home/ad/anaconda3/mkspecs/common/gcc-base.conf \
		/home/ad/anaconda3/mkspecs/common/gcc-base-unix.conf \
		/home/ad/anaconda3/mkspecs/common/g++-base.conf \
		/home/ad/anaconda3/mkspecs/common/g++-unix.conf \
		/home/ad/anaconda3/mkspecs/qconfig.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_clucene_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_concurrent.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_core.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_core_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_dbus.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_designer.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_designer_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_gui.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_gui_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_help.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_help_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_multimedia.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_network.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_network_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_nfc.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_opengl.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_printsupport.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_qml.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_qml_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_qmltest.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_quick.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_quick_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_script.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_script_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_scripttools.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_scripttools_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_sql.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_sql_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_svg.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_svg_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_testlib.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_uitools.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_webchannel.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_webkit.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_webkit_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_websockets.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_widgets.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_x11extras.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_xml.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_xml_private.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/ad/anaconda3/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/ad/anaconda3/mkspecs/features/qt_functions.prf \
		/home/ad/anaconda3/mkspecs/features/qt_config.prf \
		/home/ad/anaconda3/mkspecs/linux-g++/qmake.conf \
		/home/ad/anaconda3/mkspecs/features/spec_post.prf \
		/home/ad/anaconda3/mkspecs/features/exclusive_builds.prf \
		/home/ad/anaconda3/mkspecs/features/default_pre.prf \
		/home/ad/anaconda3/mkspecs/features/resolve_config.prf \
		/home/ad/anaconda3/mkspecs/features/default_post.prf \
		/home/ad/anaconda3/mkspecs/features/warn_on.prf \
		/home/ad/anaconda3/mkspecs/features/qt.prf \
		/home/ad/anaconda3/mkspecs/features/resources.prf \
		/home/ad/anaconda3/mkspecs/features/moc.prf \
		/home/ad/anaconda3/mkspecs/features/unix/opengl.prf \
		/home/ad/anaconda3/mkspecs/features/uic.prf \
		/home/ad/anaconda3/mkspecs/features/unix/thread.prf \
		/home/ad/anaconda3/mkspecs/features/file_copies.prf \
		/home/ad/anaconda3/mkspecs/features/testcase_targets.prf \
		/home/ad/anaconda3/mkspecs/features/exceptions.prf \
		/home/ad/anaconda3/mkspecs/features/yacc.prf \
		/home/ad/anaconda3/mkspecs/features/lex.prf \
		autoed.pro \
		/home/ad/anaconda3/lib/libQt5Widgets.prl \
		/home/ad/anaconda3/lib/libQt5Gui.prl \
		/home/ad/anaconda3/lib/libQt5Core.prl
	$(QMAKE) -o Makefile autoed.pro
/home/ad/anaconda3/mkspecs/features/spec_pre.prf:
/home/ad/anaconda3/mkspecs/common/unix.conf:
/home/ad/anaconda3/mkspecs/common/linux.conf:
/home/ad/anaconda3/mkspecs/common/sanitize.conf:
/home/ad/anaconda3/mkspecs/common/gcc-base.conf:
/home/ad/anaconda3/mkspecs/common/gcc-base-unix.conf:
/home/ad/anaconda3/mkspecs/common/g++-base.conf:
/home/ad/anaconda3/mkspecs/common/g++-unix.conf:
/home/ad/anaconda3/mkspecs/qconfig.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_bluetooth.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_bluetooth_private.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_bootstrap_private.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_clucene_private.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_concurrent.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_concurrent_private.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_core.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_core_private.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_dbus.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_dbus_private.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_designer.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_designer_private.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_designercomponents_private.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_gui.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_gui_private.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_help.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_help_private.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_multimedia.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_multimedia_private.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_multimediawidgets.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_network.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_network_private.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_nfc.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_nfc_private.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_opengl.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_opengl_private.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_openglextensions.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_openglextensions_private.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_platformsupport_private.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_printsupport.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_printsupport_private.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_qml.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_qml_private.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_qmltest.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_qmltest_private.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_quick.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_quick_private.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_quickparticles_private.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_quickwidgets.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_script.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_script_private.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_scripttools.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_scripttools_private.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_sql.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_sql_private.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_svg.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_svg_private.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_testlib.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_testlib_private.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_uiplugin.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_uitools.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_uitools_private.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_webchannel.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_webchannel_private.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_webkit.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_webkit_private.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_webkitwidgets.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_websockets.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_websockets_private.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_widgets.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_widgets_private.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_x11extras.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_x11extras_private.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_xml.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_xml_private.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_xmlpatterns.pri:
/home/ad/anaconda3/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/home/ad/anaconda3/mkspecs/features/qt_functions.prf:
/home/ad/anaconda3/mkspecs/features/qt_config.prf:
/home/ad/anaconda3/mkspecs/linux-g++/qmake.conf:
/home/ad/anaconda3/mkspecs/features/spec_post.prf:
/home/ad/anaconda3/mkspecs/features/exclusive_builds.prf:
/home/ad/anaconda3/mkspecs/features/default_pre.prf:
/home/ad/anaconda3/mkspecs/features/resolve_config.prf:
/home/ad/anaconda3/mkspecs/features/default_post.prf:
/home/ad/anaconda3/mkspecs/features/warn_on.prf:
/home/ad/anaconda3/mkspecs/features/qt.prf:
/home/ad/anaconda3/mkspecs/features/resources.prf:
/home/ad/anaconda3/mkspecs/features/moc.prf:
/home/ad/anaconda3/mkspecs/features/unix/opengl.prf:
/home/ad/anaconda3/mkspecs/features/uic.prf:
/home/ad/anaconda3/mkspecs/features/unix/thread.prf:
/home/ad/anaconda3/mkspecs/features/file_copies.prf:
/home/ad/anaconda3/mkspecs/features/testcase_targets.prf:
/home/ad/anaconda3/mkspecs/features/exceptions.prf:
/home/ad/anaconda3/mkspecs/features/yacc.prf:
/home/ad/anaconda3/mkspecs/features/lex.prf:
autoed.pro:
/home/ad/anaconda3/lib/libQt5Widgets.prl:
/home/ad/anaconda3/lib/libQt5Gui.prl:
/home/ad/anaconda3/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile autoed.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents include/mainwindow.h include/struct.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/mainwindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents forms/mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: build/moc/moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc/moc_mainwindow.cpp
build/moc/moc_mainwindow.cpp: include/mainwindow.h
	/home/ad/anaconda3/bin/moc $(DEFINES) -I/home/ad/anaconda3/mkspecs/linux-g++ -I/media/ad/Area51/workspace/assignments/cop290 -I/home/ad/anaconda3/include/qt -I/home/ad/anaconda3/include/qt/QtWidgets -I/home/ad/anaconda3/include/qt/QtGui -I/home/ad/anaconda3/include/qt/QtCore -I/home/ad/anaconda3/lib/gcc/x86_64-unknown-linux-gnu/4.8.5/include -I/home/ad/anaconda3/lib/gcc/x86_64-unknown-linux-gnu/4.8.5/include-fixed -I/home/ad/anaconda3/gcc/include/c++ -I/home/ad/anaconda3/gcc/include/c++/x86_64-unknown-linux-gnu -I/home/ad/anaconda3/gcc/include/c++/backward -I/home/ad/anaconda3/include -I/usr/include include/mainwindow.h -o build/moc/moc_mainwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: build/uic/ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) build/uic/ui_mainwindow.h
build/uic/ui_mainwindow.h: forms/mainwindow.ui
	/home/ad/anaconda3/bin/uic forms/mainwindow.ui -o build/uic/ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

build/obj/main.o: src/main.cpp include/mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/main.o src/main.cpp

build/obj/mainwindow.o: src/mainwindow.cpp include/mainwindow.h \
		build/uic/ui_mainwindow.h \
		src/draw.cpp \
		include/struct.h \
		src/threeD_to_ortho.cpp \
		src/input.cpp \
		src/twoD_to3D.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/mainwindow.o src/mainwindow.cpp

build/obj/moc_mainwindow.o: build/moc/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_mainwindow.o build/moc/moc_mainwindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

